source 'https://rubygems.org'
ruby "2.5.0"

gem 'rails', '5.0.7'
gem 'therubyracer'
gem 'execjs'

gem 'sqlite3', '1.3.13'
gem 'jquery-rails', '~> 4.0', '>= 4.0.5'

group :development, :test do
  gem 'pry-rails'
  gem 'faker', '~> 1.8', '>= 1.8.7'
  gem 'jquery-rails', '~> 4.0', '>= 4.0.5'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 5.0', '>= 5.0.7'
  gem 'coffee-rails', '~> 4.2', '>= 4.2.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end
