source 'https://rubygems.org'
ruby "1.9.3"

gem 'rails', '3.2.11'
gem 'therubyracer'
gem 'execjs'

group :development, :test do
  gem 'pry-rails'
  gem 'faker'
  gem 'jquery-rails'
end

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem "meta_search",    '>= 1.1.0.pre'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'


